### ISSUE TITLE
ValueError: unknown file extension:

### ISSUE THREAD

**Issue by Drjacky** [delimitry/collage_maker#4]
There are only `jpg` but, I get this after a while:
```python
➜  collage_maker git:(master) python3 collage_maker.py -f /ImagesAll -o /ImagesAll -w 20000 -i 50 -s
Making collage...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 2144, in save
    format = EXTENSION[ext]
KeyError: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/collage_maker/collage_maker.py", line 118, in <module>
    main()
  File "/collage_maker/collage_maker.py", line 110, in main
    res = make_collage(images, args.output, args.width, args.init_height)
  File "/collage_maker/collage_maker.py", line 80, in make_collage
    collage_image.save(filename)
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 2146, in save
    raise ValueError(f"unknown file extension: {ext}") from e
ValueError: unknown file extension:
```

Even there is no `.DS_Store` - `find . -name '.DS_Store' -type f -delete`

**Comment by Drjacky** [comment]
I forgot to add the filename to the output. Also, the output path is somewhere else and not the same as the input.
Correct command: `python3 collage_maker.py -f /ImagesAll -o /SomewhereImagesAll/result.jpg -w 20000 -i 50 -s`
